algoritmo "identificar o valor"
// Função :Ler um valor e escrever se é positivo, negativo ou zero
// Autor :
// Data : 04/07/2022
// Seção de Declarações 
var
  V: inteiro
inicio
  Escreval(" Digite um valor: ")
  Leia(V)
  Se V > 0 entao
    Escreval(" O VALOR È POSITIVO ")
  Senao
    Se V = 0 entao
       Escreval(" O VALOR È ZERO ")
  Senao
       Escreval(" O VALOR É NEGATIVO ")
  FimSe  FimSe
  FimSe
fimalgoritmo
