algoritmo "Fibonacci"

var
   T1, T2, t3, cont: Inteiro
   
Funcao  ProximoFibonacci (var A, B: Inteiro): Inteiro
Var
   c : Inteiro
Inicio
     c := A + B
      A := B
      B := C
     Retorne C
FimFuncao
inicio
      T1 <- 0
      Escreva(T2)
      T2 <- 1
      Escreva(T1)
     para cont := 3 ate 10 faca
         T3 <- ProximoFibonacci(T1, T2)
         Escreval(T3)
     FimPara
// Seção de Comandos 
fimalgoritmo
